---
- name: Windows Directory Creation and Network Info
  hosts: all
  gather_facts: false
  connection: winbatch_v2
  vars:
    ansible_shell_type: powershell
    ansible_winbatch_batch_size: 20
    ansible_winbatch_status_interval: 5
    ansible_winbatch_execution_timeout: 120
    ansible_winbatch_ssh_timeout: 60
  
  tasks:
    - name: Create multiple directories
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - C:\TestDir1
        - C:\TestDir2
        - C:\TestDir3

    - name: Get network adapter information
      ansible.windows.win_shell: |
        Get-NetAdapter | Select-Object Name, InterfaceDescription, LinkSpeed | ConvertTo-Json
      register: network_info

    - name: Display network information
      debug:
        var: network_info.stdout

    - name: Get network configuration
      win_shell: ipconfig /all
      register: ipconfig_output

    - name: Save ipconfig output to file
      win_copy:
        content: "{{ ipconfig_output.stdout }}"
        dest: C:\test\network_info.txt
