---
# WinBatch V2 SSH Connection Plugin Inventory
# Для Windows машин с SSH сервером

windows_servers:
  hosts:
    win-target-01:
      ansible_host: 192.168.1.100  # Замените на ваш Windows IP
      ansible_user: administrator   # Замените на ваш SSH user
      ansible_port: 22
      ansible_connection: winbatch_v2
      
    win-target-02:
      ansible_host: 192.168.1.101  # Замените на ваш Windows IP
      ansible_user: administrator   # Замените на ваш SSH user 
      ansible_port: 22
      ansible_connection: winbatch_v2
      
  vars:
    # WinBatch V2 Configuration
    ansible_winbatch_batch_size: 10
    ansible_winbatch_connection_timeout: 30
    ansible_winbatch_command_timeout: 300
    ansible_winbatch_persistent: true
    ansible_winbatch_shell_type: powershell
    
    # SSH Configuration
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s'
    ansible_ssh_pipelining: true
    
    # Authentication (используйте ansible-vault для паролей в продакшене)
    # ansible_password: "{{ vault_windows_password }}"
    # ansible_ssh_private_key_file: /path/to/your/ssh/private/key

# Группа для всех Windows хостов
all:
  children:
    windows_servers:
  vars:
    # Global WinBatch settings
    ansible_python_interpreter: auto_silent 