---
# WinBatch V2 Inventory - Самодостаточная версия (БЕЗ кастомного EE!)
# Этот инвентарь настраивает хосты для работы с самодостаточным WinBatch V2 плагином

windows_servers:
  hosts:
    # Пример Windows Server (замените на ваши реальные сервера)
    win-server-01:
      ansible_host: 192.168.1.101
      ansible_user: administrator
      ansible_password: "{{ vault_windows_password }}"
      # Настройки WinBatch V2 (самодостаточного плагина)
      ansible_connection: winbatch_v2
      ansible_port: 22  # SSH порт
      ansible_shell_type: powershell
      ansible_winbatch_batch_size: 20
      ansible_winbatch_status_interval: 5
      ansible_winbatch_execution_timeout: 3600
      ansible_winbatch_ssh_timeout: 60
      
    win-server-02:
      ansible_host: 192.168.1.102
      ansible_user: administrator
      ansible_password: "{{ vault_windows_password }}"
      ansible_connection: winbatch_v2
      ansible_port: 22
      ansible_shell_type: powershell
      ansible_winbatch_batch_size: 25
      ansible_winbatch_status_interval: 3
      ansible_winbatch_execution_timeout: 1800
      ansible_winbatch_ssh_timeout: 45
      
    # Тестовая машина для разработки
    win-dev-01:
      ansible_host: 192.168.1.201
      ansible_user: testuser
      ansible_password: "{{ vault_dev_password }}"
      ansible_connection: winbatch_v2
      ansible_port: 22
      ansible_shell_type: powershell
      # Увеличенные таймауты для медленной машины
      ansible_winbatch_batch_size: 10
      ansible_winbatch_status_interval: 10
      ansible_winbatch_execution_timeout: 5400
      ansible_winbatch_ssh_timeout: 120
  
  vars:
    # Глобальные настройки для всех Windows серверов
    ansible_connection: winbatch_v2  # Используем самодостаточную версию!
    ansible_shell_type: powershell
    
    # WinBatch V2 конфигурация по умолчанию
    ansible_winbatch_batch_size: 15
    ansible_winbatch_status_interval: 5
    ansible_winbatch_execution_timeout: 3600
    ansible_winbatch_ssh_timeout: 60
    
    # Настройки SSH для Windows (OpenSSH Server)
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_extra_args: '-o ControlMaster=auto -o ControlPersist=60s'
    
    # Метаданные плагина
    winbatch_plugin_version: "v2.0"
    winbatch_plugin_type: "self_contained"
    winbatch_custom_ee_required: false
    winbatch_compatible_with: "any_standard_awx_ee"
    
    # Производительность и мониторинг
    winbatch_performance_improvement: "300-500%"
    winbatch_monitoring_enabled: true
    winbatch_cleanup_after_execution: true
    
    # Функциональные возможности
    winbatch_features:
      - "Auto dependency installation"
      - "SSH connection multiplexing"  
      - "Batch task processing"
      - "Real-time status monitoring"
      - "Enhanced error handling"
      - "Standard EE compatibility"
      - "Zero configuration deployment"
    
    # Совместимость
    winbatch_compatibility:
      execution_environments:
        - "AWX Default EE"
        - "AWX Minimal EE"
        - "Custom EE (any)"
        - "Community EE"
      ansible_versions:
        - "2.9+"
        - "2.14+"
        - "2.15+"
        - "2.16+"  
      python_versions:
        - "3.8+"
        - "3.9+"
        - "3.10+"
        - "3.11+"
        - "3.12+"

# Группа для высокопроизводительных серверов
high_performance_windows:
  hosts:
    win-server-01:
    win-server-02:
  vars:
    # Оптимизированные настройки для мощных серверов
    ansible_winbatch_batch_size: 30
    ansible_winbatch_status_interval: 2
    ansible_winbatch_execution_timeout: 1800
    ansible_winbatch_ssh_timeout: 30

# Группа для тестирования и разработки
development_windows:
  hosts:
    win-dev-01:
  vars:
    # Консервативные настройки для тестовых машин
    ansible_winbatch_batch_size: 5
    ansible_winbatch_status_interval: 10
    ansible_winbatch_execution_timeout: 7200
    ansible_winbatch_ssh_timeout: 120
    # Дополнительные настройки для debugging
    ansible_verbosity: 2
    winbatch_debug_mode: true

# Все Windows хосты
all:
  children:
    windows_servers:
    high_performance_windows:
    development_windows:
  vars:
    # Глобальные переменные
    winbatch_revolution_enabled: true
    deployment_method: "git_project_based"  # Не требует кастомного EE
    deployment_complexity: "minimal"
    
    # Информация о революционных улучшениях
    performance_benefits:
      traditional_approach: "One SSH connection per task"
      winbatch_v2_approach: "One SSH connection per playbook"
      improvement_factor: "3-5x faster execution"
      resource_efficiency: "Dramatically reduced network overhead"
      
    # Инструкции по развертыванию (БЕЗ кастомного EE!)
    deployment_instructions:
      step_1: "Add plugin files to your Git project in plugins/connection/ directory"
      step_2: "Update ansible.cfg to include connection_plugins path"
      step_3: "Set ansible_connection: winbatch_v2 in inventory"
      step_4: "Create Job Template in AWX using any standard EE"
      step_5: "Execute and enjoy 3-5x performance improvement!"
      
    # Требования к системе
    system_requirements:
      awx_version: "17.0+ (any version)"
      execution_environment: "Any standard AWX EE"
      target_windows: "Windows Server 2016+ with OpenSSH Server"
      network: "SSH connectivity (port 22)"
      permissions: "Standard SSH user access" 